### PR TITLE
Move bitmonero.conf to a config subfolder

### PR DESCRIPTION
**Pull request by Prowler1000**
Move the bitmonero.conf to its own subfolder in the `app` directory to allow mounting. Allows modification of config and persistence between updates.

Closed #5 as I realized I'd like to make some personal changes on the main branch of my fork for myself that may not make sense for everyone else.

### CODE REVIEW

**Comment by jnbarlow** [comment]
Does this make the `bitmonero.conf ` show up in unraid's `appdata` folder?

**Review by jnbarlow — CHANGES_REQUESTED** [review]
So, looking into this a bit more, I think for your use case and mine we need to move things around just a tad bit more.

The config file needs to live in `/config` (sibling of `/app`) instead of a folder under `/app`.  When this is used in unraid, that folder is auto mounted and persisted.  The thing I'm not super clear on is the build order.  Does the mount merge with that directory or overwrite it?

Other apps use this folder for things, but I'm unclear on if the file is copied over at build time or at some point at runtime -- like if there is a runtime check to see if the file exists and if not copy a base version in. (not sure if the Dockerfile is too early for that)

Thoughts?

**Comment by Prowler1000** [comment]
I considered placing it in `/config` but I wasn't quite sure what that was used for. I modified the template on my unraid install to mount `/app/config` instead of `/config`.

> The thing I'm not super clear on is the build order. Does the mount merge with that directory or overwrite it?

If I understand you correctly, I believe it overwrites it, if it exists. I had an issue when launching my template after making those changes because of a missing config file.

> So maybe the change here is to leave the base file in the `monero` folder, and do the startup/runtime check to see if it exists in `/config`, and if not, move it there, then start as normal

I think that is probably best, as mounting definitely happens after the image is built (image is built by GitHub Actions, then layers are pulled by Unraid). I'll make the changes, but copy rather than move, and rename the original file to something indicating it's the default `.conf`.

**Comment by Prowler1000** [comment]
I've made the changes. Briefly tested them on the main branch of my fork. File was copied if it didn't exist and an already existing file was not overwritten.

Let me know what you think

**Review by jnbarlow — APPROVED** [review]

**Pull request merged**
